// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu0tMI7G3B9en0N1DKSAH_NlYYuj-hl-o',
    appId: '1:9551219558:web:dbbf1d394618f1c5c016a7',
    messagingSenderId: '9551219558',
    projectId: 'eventos-sociales-f6e1a',
    authDomain: 'eventos-sociales-f6e1a.firebaseapp.com',
    storageBucket: 'eventos-sociales-f6e1a.appspot.com',
    measurementId: 'G-77VD4SGZK5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc8t71Xdmb89esaWoM5fxcw3FuR5aNDz8',
    appId: '1:9551219558:android:f3c9638303d67a28c016a7',
    messagingSenderId: '9551219558',
    projectId: 'eventos-sociales-f6e1a',
    storageBucket: 'eventos-sociales-f6e1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFZ3qM-YFneeSWk0aV9C6Kq71w5VnrllM',
    appId: '1:9551219558:ios:a2fd4e1c190cdd95c016a7',
    messagingSenderId: '9551219558',
    projectId: 'eventos-sociales-f6e1a',
    storageBucket: 'eventos-sociales-f6e1a.appspot.com',
    iosBundleId: 'com.example.eventosSociales',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFZ3qM-YFneeSWk0aV9C6Kq71w5VnrllM',
    appId: '1:9551219558:ios:a2fd4e1c190cdd95c016a7',
    messagingSenderId: '9551219558',
    projectId: 'eventos-sociales-f6e1a',
    storageBucket: 'eventos-sociales-f6e1a.appspot.com',
    iosBundleId: 'com.example.eventosSociales',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBu0tMI7G3B9en0N1DKSAH_NlYYuj-hl-o',
    appId: '1:9551219558:web:dfc0373233f755bec016a7',
    messagingSenderId: '9551219558',
    projectId: 'eventos-sociales-f6e1a',
    authDomain: 'eventos-sociales-f6e1a.firebaseapp.com',
    storageBucket: 'eventos-sociales-f6e1a.appspot.com',
    measurementId: 'G-8JPWNCYST3',
  );
}
